using Crucible.Generators.Analysis;
using Crucible.Generators.Emit;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Crucible.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class CrucibleGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var aggregates = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Crucible.Domain.Attributes.AggregateAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => (Class: (ClassDeclarationSyntax)ctx.TargetNode, Symbol: (INamedTypeSymbol)ctx.TargetSymbol))
            .Where(t => t.Symbol is not null);

        var combined = aggregates.Combine(context.CompilationProvider);

        context.RegisterSourceOutput(combined, (spc, pair) =>
        {
            var ((classSyntax, classSymbol), compilation) = pair;
            var analysis = AggregateAnalyzer.Analyze(classSymbol, classSyntax);

            foreach (var d in analysis.Diagnostics) spc.ReportDiagnostic(d);
            if (analysis.Model is null) return;

            var (resolvedSteps, handlerDiagnostics) = HandlerResolver.Resolve(analysis.Model, compilation, classSyntax.Identifier.GetLocation());
            foreach (var d in handlerDiagnostics) spc.ReportDiagnostic(d);

            var model = analysis.Model with { Steps = resolvedSteps };

            var cb = new CodeBuilder();
            cb.Line("// <auto-generated />");
            cb.Line("#nullable enable");
            cb.Line();
            if (!string.IsNullOrEmpty(model.Namespace))
            {
                cb.Line($"namespace {model.Namespace};");
                cb.Line();
            }

            EntryEmitter.Emit(cb, model);
            cb.Line();
            PhaseEmitter.Emit(cb, model);
            cb.Line();
            ExtensionEmitter.Emit(cb, model);
            cb.Line();
            StepEmitter.Emit(cb, model);
            cb.Line();
            RegistrationEmitter.Emit(cb, model);

            spc.AddSource($"Crucible.{model.ClassName}.g.cs", cb.ToString());
        });
    }
}
