using Crucible.Generators.Analysis;
using Crucible.Generators.Emit;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Crucible.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class CrucibleGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Aggregates
        var aggregates = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Crucible.Domain.Attributes.AggregateAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => (Class: (ClassDeclarationSyntax)ctx.TargetNode, Symbol: (INamedTypeSymbol)ctx.TargetSymbol))
            .Where(t => t.Symbol is not null);

        var aggregatesCombined = aggregates.Combine(context.CompilationProvider);

        context.RegisterSourceOutput(aggregatesCombined, (spc, pair) =>
        {
            var ((classSyntax, classSymbol), compilation) = pair;
            EmitForAggregate(spc, classSyntax, classSymbol, compilation);
        });

        // Entities
        var entities = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Crucible.Domain.Attributes.EntityAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => (Class: (ClassDeclarationSyntax)ctx.TargetNode, Symbol: (INamedTypeSymbol)ctx.TargetSymbol))
            .Where(t => t.Symbol is not null);

        context.RegisterSourceOutput(entities, (spc, pair) =>
        {
            var (classSyntax, classSymbol) = pair;
            EmitForEntity(spc, classSyntax, classSymbol);
        });
    }

    private static void EmitForAggregate(
        SourceProductionContext spc,
        ClassDeclarationSyntax classSyntax,
        INamedTypeSymbol classSymbol,
        Compilation compilation)
    {
        var analysis = AggregateAnalyzer.Analyze(classSymbol, classSyntax);

        foreach (var d in analysis.Diagnostics) spc.ReportDiagnostic(d);
        if (analysis.Model is null) return;

        var (resolvedSteps, handlerDiagnostics) = HandlerResolver.Resolve(analysis.Model, compilation, classSyntax.Identifier.GetLocation());
        foreach (var d in handlerDiagnostics) spc.ReportDiagnostic(d);

        var model = analysis.Model with { Steps = resolvedSteps };

        var cb = new CodeBuilder();
        cb.Line("// <auto-generated />");
        cb.Line("#nullable enable");
        cb.Line();
        if (!string.IsNullOrEmpty(model.Namespace))
        {
            cb.Line($"namespace {model.Namespace};");
            cb.Line();
        }

        SnapshotEmitter.Emit(cb, model);
        cb.Line();
        EntryEmitter.Emit(cb, model);
        cb.Line();
        ExtensionEmitter.Emit(cb, model);
        cb.Line();
        StepEmitter.Emit(cb, model);
        cb.Line();
        RegistrationEmitter.Emit(cb, model);

        spc.AddSource($"Crucible.{model.ClassName}.g.cs", cb.ToString());
    }

    private static void EmitForEntity(
        SourceProductionContext spc,
        ClassDeclarationSyntax classSyntax,
        INamedTypeSymbol classSymbol)
    {
        var analysis = EntityAnalyzer.Analyze(classSymbol, classSyntax);

        foreach (var d in analysis.Diagnostics) spc.ReportDiagnostic(d);
        if (analysis.Model is null) return;

        var cb = new CodeBuilder();
        cb.Line("// <auto-generated />");
        cb.Line("#nullable enable");
        cb.Line();
        if (!string.IsNullOrEmpty(analysis.Model.Namespace))
        {
            cb.Line($"namespace {analysis.Model.Namespace};");
            cb.Line();
        }

        EntityEmitter.Emit(cb, analysis.Model);

        spc.AddSource($"Crucible.{analysis.Model.ClassName}.Entity.g.cs", cb.ToString());
    }
}
