using Crucible.Domain.Events;
using FluentAssertions;
using Xunit;

namespace Crucible.Domain.Tests.Events;

public sealed class DomainEventTests
{
    private sealed record Sample(string Name) : DomainEvent;

    [Fact]
    public void EventId_IsAutoGeneratedAndDistinct()
    {
        var a = new Sample("a");
        var b = new Sample("b");
        a.EventId.Should().NotBe(Guid.Empty);
        b.EventId.Should().NotBe(a.EventId);
    }

    [Fact]
    public void OccurredAt_IsCloseToUtcNow()
    {
        var before = DateTimeOffset.UtcNow;
        var e = new Sample("x");
        var after = DateTimeOffset.UtcNow;
        e.OccurredAt.Should().BeOnOrAfter(before).And.BeOnOrBefore(after);
    }

    [Fact]
    public void DomainEvent_ImplementsIDomainEvent()
    {
        IDomainEvent e = new Sample("x");
        e.EventId.Should().NotBe(Guid.Empty);
    }
}
