//HintName: Crucible.Order.g.cs
// <auto-generated />
#nullable enable

namespace Sample;

public static class Orders
{
    public static IOrderAfterCreate Create(Sample.OrderDto dto)
    {
        return (IOrderAfterCreate)global::Crucible.Chains.Stages.ChainBuilder.Begin<global::Sample.Order, Sample.OrderId, Sample.OrderCreated>(new __Step_Create(dto));
    }
}

public interface IOrderAfterCreate : global::Crucible.Chains.Stages.IChainStage<global::Sample.Order, Sample.OrderId, Sample.OrderCreated> { }
public interface IOrderAfterPlaceOrder : global::Crucible.Chains.Stages.IChainStage<global::Sample.Order, Sample.OrderId, Sample.OrderPlaced> { }

public static class OrderChainExtensions
{
    extension(IOrderAfterCreate stage)
    {
        public IOrderAfterPlaceOrder PlaceOrder()
        {
            return (IOrderAfterPlaceOrder)global::Crucible.Chains.Stages.ChainBuilder.AppendStep<global::Sample.Order, Sample.OrderId, Sample.OrderCreated, Sample.OrderPlaced>(stage, new __Step_PlaceOrder());
        }
        public IOrderAfterCreate Tap(global::System.Action<Sample.OrderCreated> action)
        {
            return (IOrderAfterCreate)stage.Tap(action);
        }
        public IOrderAfterCreate Tap(global::System.Func<Sample.OrderCreated, global::System.IServiceProvider, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task> action)
        {
            return (IOrderAfterCreate)stage.Tap(action);
        }
        public IOrderAfterCreate OnError(global::System.Action<global::System.Collections.Generic.IReadOnlyList<global::Crucible.Domain.Errors.Error>> action)
        {
            return (IOrderAfterCreate)stage.OnError(action);
        }
        public IOrderAfterCreate ProducedEvents(global::System.Action<global::System.Collections.Generic.IReadOnlyList<global::Crucible.Domain.Events.IDomainEvent>> callback, bool drain = true)
        {
            return (IOrderAfterCreate)stage.ProducedEvents(callback, drain);
        }
        public IOrderAfterCreate DispatchEvents()
        {
            return (IOrderAfterCreate)stage.DispatchEvents();
        }
    }
    extension(IOrderAfterPlaceOrder stage)
    {
        public IOrderAfterPlaceOrder Tap(global::System.Action<Sample.OrderPlaced> action)
        {
            return (IOrderAfterPlaceOrder)stage.Tap(action);
        }
        public IOrderAfterPlaceOrder Tap(global::System.Func<Sample.OrderPlaced, global::System.IServiceProvider, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task> action)
        {
            return (IOrderAfterPlaceOrder)stage.Tap(action);
        }
        public IOrderAfterPlaceOrder OnError(global::System.Action<global::System.Collections.Generic.IReadOnlyList<global::Crucible.Domain.Errors.Error>> action)
        {
            return (IOrderAfterPlaceOrder)stage.OnError(action);
        }
        public IOrderAfterPlaceOrder ProducedEvents(global::System.Action<global::System.Collections.Generic.IReadOnlyList<global::Crucible.Domain.Events.IDomainEvent>> callback, bool drain = true)
        {
            return (IOrderAfterPlaceOrder)stage.ProducedEvents(callback, drain);
        }
        public IOrderAfterPlaceOrder DispatchEvents()
        {
            return (IOrderAfterPlaceOrder)stage.DispatchEvents();
        }
    }
}

internal sealed class __Step_Create : global::Crucible.Chains.Steps.IStep<global::Sample.Order, Sample.OrderId>
{
    private readonly Sample.OrderDto _dto; 
    public __Step_Create(Sample.OrderDto dto) { this._dto = dto; }
    public global::Crucible.Chains.Steps.StepKind Kind => global::Crucible.Chains.Steps.StepKind.AggregateMethod;
    public string Name => "Order.Create";
    public async global::System.Threading.Tasks.Task<global::Crucible.Chains.Steps.StepOutcome> InvokeAsync(global::Crucible.Chains.Steps.StepContext<global::Sample.Order, Sample.OrderId> ctx, global::System.Threading.CancellationToken ct)
    {
        ctx.Aggregate = new global::Sample.Order();
        var aggregate = ctx.Aggregate ?? throw new global::System.InvalidOperationException("Aggregate is null");
        var domainResult = aggregate.Create(this._dto);
        if (domainResult.IsFailure) return global::Crucible.Chains.Steps.StepOutcome.Failure(domainResult.Errors);
        return global::Crucible.Chains.Steps.StepOutcome.Success((object)domainResult.Value!);
    }
}
internal sealed class __Step_PlaceOrder : global::Crucible.Chains.Steps.IStep<global::Sample.Order, Sample.OrderId>
{
    public __Step_PlaceOrder() {  }
    public global::Crucible.Chains.Steps.StepKind Kind => global::Crucible.Chains.Steps.StepKind.AggregateMethod;
    public string Name => "Order.PlaceOrder";
    public async global::System.Threading.Tasks.Task<global::Crucible.Chains.Steps.StepOutcome> InvokeAsync(global::Crucible.Chains.Steps.StepContext<global::Sample.Order, Sample.OrderId> ctx, global::System.Threading.CancellationToken ct)
    {
        var aggregate = ctx.Aggregate ?? throw new global::System.InvalidOperationException("Aggregate is null");
        var domainResult = aggregate.PlaceOrder();
        if (domainResult.IsFailure) return global::Crucible.Chains.Steps.StepOutcome.Failure(domainResult.Errors);
        return global::Crucible.Chains.Steps.StepOutcome.Success((object)domainResult.Value!);
    }
}

public static class OrderAggregateRegistration
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddOrderAggregate(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        return services;
    }
}
