//HintName: Crucible.Order.g.cs
// <auto-generated />
#nullable enable

namespace Sample;

public interface IOrderSnapshot
{
    Sample.OrderId Id { get; }
    long Version { get; }
}

public partial class Order
{
    internal static global::Sample.Order __CreateForChain() => new global::Sample.Order();

    internal void __HydrateFromSnapshot(IOrderSnapshot snapshot)
    {
        Id = snapshot.Id;
        RestoreVersion(snapshot.Version);
    }
}

public static class Orders
{
    public static global::Crucible.Chains.Stages.IChainStage<global::Sample.Order, Sample.OrderId, Sample.OrderCreated> Create(Sample.OrderDto dto)
    {
        return global::Crucible.Chains.Stages.ChainBuilder.Begin<global::Sample.Order, Sample.OrderId, Sample.OrderCreated>(new __Step_Create(dto));
    }
    public static global::Crucible.Chains.Stages.IChainStage<global::Sample.Order, Sample.OrderId, Sample.OrderCreated> ReconstructAtCreate(global::Sample.IOrderSnapshot snapshot)
    {
        return global::Crucible.Chains.Stages.ChainBuilder.Begin<global::Sample.Order, Sample.OrderId, Sample.OrderCreated>(new __Step_ReconstructAtCreate(snapshot));
    }
    public static global::Crucible.Chains.Stages.IChainStage<global::Sample.Order, Sample.OrderId, Sample.OrderApproved> ReconstructAtApprove(global::Sample.IOrderSnapshot snapshot)
    {
        return global::Crucible.Chains.Stages.ChainBuilder.Begin<global::Sample.Order, Sample.OrderId, Sample.OrderApproved>(new __Step_ReconstructAtApprove(snapshot));
    }
    public static global::Crucible.Chains.Stages.IChainStage<global::Sample.Order, Sample.OrderId, Sample.OrderRejected> ReconstructAtReject(global::Sample.IOrderSnapshot snapshot)
    {
        return global::Crucible.Chains.Stages.ChainBuilder.Begin<global::Sample.Order, Sample.OrderId, Sample.OrderRejected>(new __Step_ReconstructAtReject(snapshot));
    }
    public static global::Crucible.Chains.Stages.IChainStage<global::Sample.Order, Sample.OrderId, Sample.OrderPlaced> ReconstructAtPlace(global::Sample.IOrderSnapshot snapshot)
    {
        return global::Crucible.Chains.Stages.ChainBuilder.Begin<global::Sample.Order, Sample.OrderId, Sample.OrderPlaced>(new __Step_ReconstructAtPlace(snapshot));
    }
    public static global::Crucible.Chains.Stages.IChainStage<global::Sample.Order, Sample.OrderId, Sample.OrderCancelled> ReconstructAtCancel(global::Sample.IOrderSnapshot snapshot)
    {
        return global::Crucible.Chains.Stages.ChainBuilder.Begin<global::Sample.Order, Sample.OrderId, Sample.OrderCancelled>(new __Step_ReconstructAtCancel(snapshot));
    }
}

public static class OrderChainExtensions
{
    extension(global::Crucible.Chains.Stages.IChainStage<global::Sample.Order, Sample.OrderId, Sample.OrderCreated> stage)
    {
        public global::Crucible.Chains.Stages.IChainStage<global::Sample.Order, Sample.OrderId, Sample.OrderApproved> Approve(string approver)
        {
            return global::Crucible.Chains.Stages.ChainBuilder.AppendStep<global::Sample.Order, Sample.OrderId, Sample.OrderCreated, Sample.OrderApproved>(stage, new __Step_Approve(approver));
        }
        public global::Crucible.Chains.Stages.IChainStage<global::Sample.Order, Sample.OrderId, Sample.OrderRejected> Reject(string reason)
        {
            return global::Crucible.Chains.Stages.ChainBuilder.AppendStep<global::Sample.Order, Sample.OrderId, Sample.OrderCreated, Sample.OrderRejected>(stage, new __Step_Reject(reason));
        }
    }
    extension(global::Crucible.Chains.Stages.IChainStage<global::Sample.Order, Sample.OrderId, Sample.OrderApproved> stage)
    {
        public global::Crucible.Chains.Stages.IChainStage<global::Sample.Order, Sample.OrderId, Sample.OrderPlaced> Place()
        {
            return global::Crucible.Chains.Stages.ChainBuilder.AppendStep<global::Sample.Order, Sample.OrderId, Sample.OrderApproved, Sample.OrderPlaced>(stage, new __Step_Place());
        }
    }
    extension(global::Crucible.Chains.Stages.IChainStage<global::Sample.Order, Sample.OrderId, Sample.OrderRejected> stage)
    {
        public global::Crucible.Chains.Stages.IChainStage<global::Sample.Order, Sample.OrderId, Sample.OrderCancelled> Cancel()
        {
            return global::Crucible.Chains.Stages.ChainBuilder.AppendStep<global::Sample.Order, Sample.OrderId, Sample.OrderRejected, Sample.OrderCancelled>(stage, new __Step_Cancel());
        }
    }
    extension(global::Crucible.Chains.Stages.IChainStage<global::Sample.Order, Sample.OrderId, Sample.OrderPlaced> stage)
    {
    }
    extension(global::Crucible.Chains.Stages.IChainStage<global::Sample.Order, Sample.OrderId, Sample.OrderCancelled> stage)
    {
    }
}

internal sealed class __Step_Create : global::Crucible.Chains.Steps.IStep<global::Sample.Order, Sample.OrderId>
{
    private readonly Sample.OrderDto _dto; 
    public __Step_Create(Sample.OrderDto dto) { this._dto = dto; }
    public global::Crucible.Chains.Steps.StepKind Kind => global::Crucible.Chains.Steps.StepKind.AggregateMethod;
    public string Name => "Order.Create";
    public async global::System.Threading.Tasks.Task<global::Crucible.Chains.Steps.StepOutcome> InvokeAsync(global::Crucible.Chains.Steps.StepContext<global::Sample.Order, Sample.OrderId> ctx, global::System.Threading.CancellationToken ct)
    {
        ctx.Aggregate = global::Sample.Order.__CreateForChain();
        var aggregate = ctx.Aggregate ?? throw new global::System.InvalidOperationException("Aggregate is null");
        var domainResult = aggregate.Create(this._dto);
        if (domainResult.IsFailure) return global::Crucible.Chains.Steps.StepOutcome.Failure(domainResult.Errors);
        return global::Crucible.Chains.Steps.StepOutcome.Success((object)domainResult.Value!);
    }
}
internal sealed class __Step_Approve : global::Crucible.Chains.Steps.IStep<global::Sample.Order, Sample.OrderId>
{
    private readonly string _approver; 
    public __Step_Approve(string approver) { this._approver = approver; }
    public global::Crucible.Chains.Steps.StepKind Kind => global::Crucible.Chains.Steps.StepKind.AggregateMethod;
    public string Name => "Order.Approve";
    public async global::System.Threading.Tasks.Task<global::Crucible.Chains.Steps.StepOutcome> InvokeAsync(global::Crucible.Chains.Steps.StepContext<global::Sample.Order, Sample.OrderId> ctx, global::System.Threading.CancellationToken ct)
    {
        var aggregate = ctx.Aggregate ?? throw new global::System.InvalidOperationException("Aggregate is null");
        var domainResult = aggregate.Approve(this._approver);
        if (domainResult.IsFailure) return global::Crucible.Chains.Steps.StepOutcome.Failure(domainResult.Errors);
        return global::Crucible.Chains.Steps.StepOutcome.Success((object)domainResult.Value!);
    }
}
internal sealed class __Step_Reject : global::Crucible.Chains.Steps.IStep<global::Sample.Order, Sample.OrderId>
{
    private readonly string _reason; 
    public __Step_Reject(string reason) { this._reason = reason; }
    public global::Crucible.Chains.Steps.StepKind Kind => global::Crucible.Chains.Steps.StepKind.AggregateMethod;
    public string Name => "Order.Reject";
    public async global::System.Threading.Tasks.Task<global::Crucible.Chains.Steps.StepOutcome> InvokeAsync(global::Crucible.Chains.Steps.StepContext<global::Sample.Order, Sample.OrderId> ctx, global::System.Threading.CancellationToken ct)
    {
        var aggregate = ctx.Aggregate ?? throw new global::System.InvalidOperationException("Aggregate is null");
        var domainResult = aggregate.Reject(this._reason);
        if (domainResult.IsFailure) return global::Crucible.Chains.Steps.StepOutcome.Failure(domainResult.Errors);
        return global::Crucible.Chains.Steps.StepOutcome.Success((object)domainResult.Value!);
    }
}
internal sealed class __Step_Place : global::Crucible.Chains.Steps.IStep<global::Sample.Order, Sample.OrderId>
{
    public __Step_Place() {  }
    public global::Crucible.Chains.Steps.StepKind Kind => global::Crucible.Chains.Steps.StepKind.AggregateMethod;
    public string Name => "Order.Place";
    public async global::System.Threading.Tasks.Task<global::Crucible.Chains.Steps.StepOutcome> InvokeAsync(global::Crucible.Chains.Steps.StepContext<global::Sample.Order, Sample.OrderId> ctx, global::System.Threading.CancellationToken ct)
    {
        var aggregate = ctx.Aggregate ?? throw new global::System.InvalidOperationException("Aggregate is null");
        var domainResult = aggregate.Place();
        if (domainResult.IsFailure) return global::Crucible.Chains.Steps.StepOutcome.Failure(domainResult.Errors);
        return global::Crucible.Chains.Steps.StepOutcome.Success((object)domainResult.Value!);
    }
}
internal sealed class __Step_Cancel : global::Crucible.Chains.Steps.IStep<global::Sample.Order, Sample.OrderId>
{
    public __Step_Cancel() {  }
    public global::Crucible.Chains.Steps.StepKind Kind => global::Crucible.Chains.Steps.StepKind.AggregateMethod;
    public string Name => "Order.Cancel";
    public async global::System.Threading.Tasks.Task<global::Crucible.Chains.Steps.StepOutcome> InvokeAsync(global::Crucible.Chains.Steps.StepContext<global::Sample.Order, Sample.OrderId> ctx, global::System.Threading.CancellationToken ct)
    {
        var aggregate = ctx.Aggregate ?? throw new global::System.InvalidOperationException("Aggregate is null");
        var domainResult = aggregate.Cancel();
        if (domainResult.IsFailure) return global::Crucible.Chains.Steps.StepOutcome.Failure(domainResult.Errors);
        return global::Crucible.Chains.Steps.StepOutcome.Success((object)domainResult.Value!);
    }
}
internal sealed class __Step_ReconstructAtCreate : global::Crucible.Chains.Steps.IStep<global::Sample.Order, Sample.OrderId>
{
    private readonly global::Sample.IOrderSnapshot _snapshot;
    public __Step_ReconstructAtCreate(global::Sample.IOrderSnapshot snapshot) { this._snapshot = snapshot; }
    public global::Crucible.Chains.Steps.StepKind Kind => global::Crucible.Chains.Steps.StepKind.AggregateMethod;
    public string Name => "Order.ReconstructAtCreate";
    public global::System.Threading.Tasks.Task<global::Crucible.Chains.Steps.StepOutcome> InvokeAsync(global::Crucible.Chains.Steps.StepContext<global::Sample.Order, Sample.OrderId> ctx, global::System.Threading.CancellationToken ct)
    {
        var aggregate = global::Sample.Order.__CreateForChain();
        aggregate.__HydrateFromSnapshot(this._snapshot);
        ctx.Aggregate = aggregate;
        return global::System.Threading.Tasks.Task.FromResult(global::Crucible.Chains.Steps.StepOutcome.Success());
    }
}
internal sealed class __Step_ReconstructAtApprove : global::Crucible.Chains.Steps.IStep<global::Sample.Order, Sample.OrderId>
{
    private readonly global::Sample.IOrderSnapshot _snapshot;
    public __Step_ReconstructAtApprove(global::Sample.IOrderSnapshot snapshot) { this._snapshot = snapshot; }
    public global::Crucible.Chains.Steps.StepKind Kind => global::Crucible.Chains.Steps.StepKind.AggregateMethod;
    public string Name => "Order.ReconstructAtApprove";
    public global::System.Threading.Tasks.Task<global::Crucible.Chains.Steps.StepOutcome> InvokeAsync(global::Crucible.Chains.Steps.StepContext<global::Sample.Order, Sample.OrderId> ctx, global::System.Threading.CancellationToken ct)
    {
        var aggregate = global::Sample.Order.__CreateForChain();
        aggregate.__HydrateFromSnapshot(this._snapshot);
        ctx.Aggregate = aggregate;
        return global::System.Threading.Tasks.Task.FromResult(global::Crucible.Chains.Steps.StepOutcome.Success());
    }
}
internal sealed class __Step_ReconstructAtReject : global::Crucible.Chains.Steps.IStep<global::Sample.Order, Sample.OrderId>
{
    private readonly global::Sample.IOrderSnapshot _snapshot;
    public __Step_ReconstructAtReject(global::Sample.IOrderSnapshot snapshot) { this._snapshot = snapshot; }
    public global::Crucible.Chains.Steps.StepKind Kind => global::Crucible.Chains.Steps.StepKind.AggregateMethod;
    public string Name => "Order.ReconstructAtReject";
    public global::System.Threading.Tasks.Task<global::Crucible.Chains.Steps.StepOutcome> InvokeAsync(global::Crucible.Chains.Steps.StepContext<global::Sample.Order, Sample.OrderId> ctx, global::System.Threading.CancellationToken ct)
    {
        var aggregate = global::Sample.Order.__CreateForChain();
        aggregate.__HydrateFromSnapshot(this._snapshot);
        ctx.Aggregate = aggregate;
        return global::System.Threading.Tasks.Task.FromResult(global::Crucible.Chains.Steps.StepOutcome.Success());
    }
}
internal sealed class __Step_ReconstructAtPlace : global::Crucible.Chains.Steps.IStep<global::Sample.Order, Sample.OrderId>
{
    private readonly global::Sample.IOrderSnapshot _snapshot;
    public __Step_ReconstructAtPlace(global::Sample.IOrderSnapshot snapshot) { this._snapshot = snapshot; }
    public global::Crucible.Chains.Steps.StepKind Kind => global::Crucible.Chains.Steps.StepKind.AggregateMethod;
    public string Name => "Order.ReconstructAtPlace";
    public global::System.Threading.Tasks.Task<global::Crucible.Chains.Steps.StepOutcome> InvokeAsync(global::Crucible.Chains.Steps.StepContext<global::Sample.Order, Sample.OrderId> ctx, global::System.Threading.CancellationToken ct)
    {
        var aggregate = global::Sample.Order.__CreateForChain();
        aggregate.__HydrateFromSnapshot(this._snapshot);
        ctx.Aggregate = aggregate;
        return global::System.Threading.Tasks.Task.FromResult(global::Crucible.Chains.Steps.StepOutcome.Success());
    }
}
internal sealed class __Step_ReconstructAtCancel : global::Crucible.Chains.Steps.IStep<global::Sample.Order, Sample.OrderId>
{
    private readonly global::Sample.IOrderSnapshot _snapshot;
    public __Step_ReconstructAtCancel(global::Sample.IOrderSnapshot snapshot) { this._snapshot = snapshot; }
    public global::Crucible.Chains.Steps.StepKind Kind => global::Crucible.Chains.Steps.StepKind.AggregateMethod;
    public string Name => "Order.ReconstructAtCancel";
    public global::System.Threading.Tasks.Task<global::Crucible.Chains.Steps.StepOutcome> InvokeAsync(global::Crucible.Chains.Steps.StepContext<global::Sample.Order, Sample.OrderId> ctx, global::System.Threading.CancellationToken ct)
    {
        var aggregate = global::Sample.Order.__CreateForChain();
        aggregate.__HydrateFromSnapshot(this._snapshot);
        ctx.Aggregate = aggregate;
        return global::System.Threading.Tasks.Task.FromResult(global::Crucible.Chains.Steps.StepOutcome.Success());
    }
}

public static class OrderAggregateRegistration
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddOrderAggregate(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        return services;
    }
}
