//HintName: Crucible.Order.g.cs
// <auto-generated />
#nullable enable

namespace Sample;

public interface IOrderSnapshot
{
    Sample.OrderId Id { get; }
    long Version { get; }
}

public partial class Order
{
    internal static global::Sample.Order __CreateForChain() => new global::Sample.Order();

    internal void __HydrateFromSnapshot(IOrderSnapshot snapshot)
    {
        Id = snapshot.Id;
        RestoreVersion(snapshot.Version);
    }
}

public static class Orders
{
    public static global::Crucible.Chains.Stages.IChainStage<global::Sample.Order, Sample.OrderId, Sample.OrderCreated> Create(Sample.OrderDto dto)
    {
        return global::Crucible.Chains.Stages.ChainBuilder.Begin<global::Sample.Order, Sample.OrderId, Sample.OrderCreated>(new __Step_Create(dto));
    }
    public static global::Crucible.Chains.Stages.IChainStage<global::Sample.Order, Sample.OrderId, Sample.OrderCreated> ReconstructAtCreate(global::Sample.IOrderSnapshot snapshot)
    {
        return global::Crucible.Chains.Stages.ChainBuilder.Begin<global::Sample.Order, Sample.OrderId, Sample.OrderCreated>(new __Step_ReconstructAtCreate(snapshot));
    }
    public static global::Crucible.Chains.Stages.IChainStage<global::Sample.Order, Sample.OrderId, Sample.OrderPlaced> ReconstructAtPlaceOrder(global::Sample.IOrderSnapshot snapshot)
    {
        return global::Crucible.Chains.Stages.ChainBuilder.Begin<global::Sample.Order, Sample.OrderId, Sample.OrderPlaced>(new __Step_ReconstructAtPlaceOrder(snapshot));
    }
}

public static class OrderChainExtensions
{
    extension(global::Crucible.Chains.Stages.IChainStage<global::Sample.Order, Sample.OrderId, Sample.OrderCreated> stage)
    {
        public global::Crucible.Chains.Stages.IChainStage<global::Sample.Order, Sample.OrderId, Sample.OrderPlaced> PlaceOrder()
        {
            return global::Crucible.Chains.Stages.ChainBuilder.AppendStep<global::Sample.Order, Sample.OrderId, Sample.OrderCreated, Sample.OrderPlaced>(stage, new __Step_PlaceOrder());
        }
    }
    extension(global::Crucible.Chains.Stages.IChainStage<global::Sample.Order, Sample.OrderId, Sample.OrderPlaced> stage)
    {
    }
}

internal sealed class __Step_Create : global::Crucible.Chains.Steps.IStep<global::Sample.Order, Sample.OrderId>
{
    private readonly Sample.OrderDto _dto; 
    public __Step_Create(Sample.OrderDto dto) { this._dto = dto; }
    public global::Crucible.Chains.Steps.StepKind Kind => global::Crucible.Chains.Steps.StepKind.AggregateMethod;
    public string Name => "Order.Create";
    public async global::System.Threading.Tasks.Task<global::Crucible.Chains.Steps.StepOutcome> InvokeAsync(global::Crucible.Chains.Steps.StepContext<global::Sample.Order, Sample.OrderId> ctx, global::System.Threading.CancellationToken ct)
    {
        ctx.Aggregate = global::Sample.Order.__CreateForChain();
        var aggregate = ctx.Aggregate ?? throw new global::System.InvalidOperationException("Aggregate is null");
        var domainResult = aggregate.Create(this._dto);
        if (domainResult.IsFailure) return global::Crucible.Chains.Steps.StepOutcome.Failure(domainResult.Errors);
        return global::Crucible.Chains.Steps.StepOutcome.Success((object)domainResult.Value!);
    }
}
internal sealed class __Step_PlaceOrder : global::Crucible.Chains.Steps.IStep<global::Sample.Order, Sample.OrderId>
{
    public __Step_PlaceOrder() {  }
    public global::Crucible.Chains.Steps.StepKind Kind => global::Crucible.Chains.Steps.StepKind.AggregateMethod;
    public string Name => "Order.PlaceOrder";
    public async global::System.Threading.Tasks.Task<global::Crucible.Chains.Steps.StepOutcome> InvokeAsync(global::Crucible.Chains.Steps.StepContext<global::Sample.Order, Sample.OrderId> ctx, global::System.Threading.CancellationToken ct)
    {
        var aggregate = ctx.Aggregate ?? throw new global::System.InvalidOperationException("Aggregate is null");
        var domainResult = aggregate.PlaceOrder();
        if (domainResult.IsFailure) return global::Crucible.Chains.Steps.StepOutcome.Failure(domainResult.Errors);
        return global::Crucible.Chains.Steps.StepOutcome.Success((object)domainResult.Value!);
    }
}
internal sealed class __Step_ReconstructAtCreate : global::Crucible.Chains.Steps.IStep<global::Sample.Order, Sample.OrderId>
{
    private readonly global::Sample.IOrderSnapshot _snapshot;
    public __Step_ReconstructAtCreate(global::Sample.IOrderSnapshot snapshot) { this._snapshot = snapshot; }
    public global::Crucible.Chains.Steps.StepKind Kind => global::Crucible.Chains.Steps.StepKind.AggregateMethod;
    public string Name => "Order.ReconstructAtCreate";
    public global::System.Threading.Tasks.Task<global::Crucible.Chains.Steps.StepOutcome> InvokeAsync(global::Crucible.Chains.Steps.StepContext<global::Sample.Order, Sample.OrderId> ctx, global::System.Threading.CancellationToken ct)
    {
        var aggregate = global::Sample.Order.__CreateForChain();
        aggregate.__HydrateFromSnapshot(this._snapshot);
        ctx.Aggregate = aggregate;
        return global::System.Threading.Tasks.Task.FromResult(global::Crucible.Chains.Steps.StepOutcome.Success());
    }
}
internal sealed class __Step_ReconstructAtPlaceOrder : global::Crucible.Chains.Steps.IStep<global::Sample.Order, Sample.OrderId>
{
    private readonly global::Sample.IOrderSnapshot _snapshot;
    public __Step_ReconstructAtPlaceOrder(global::Sample.IOrderSnapshot snapshot) { this._snapshot = snapshot; }
    public global::Crucible.Chains.Steps.StepKind Kind => global::Crucible.Chains.Steps.StepKind.AggregateMethod;
    public string Name => "Order.ReconstructAtPlaceOrder";
    public global::System.Threading.Tasks.Task<global::Crucible.Chains.Steps.StepOutcome> InvokeAsync(global::Crucible.Chains.Steps.StepContext<global::Sample.Order, Sample.OrderId> ctx, global::System.Threading.CancellationToken ct)
    {
        var aggregate = global::Sample.Order.__CreateForChain();
        aggregate.__HydrateFromSnapshot(this._snapshot);
        ctx.Aggregate = aggregate;
        return global::System.Threading.Tasks.Task.FromResult(global::Crucible.Chains.Steps.StepOutcome.Success());
    }
}

public static class OrderAggregateRegistration
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddOrderAggregate(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        return services;
    }
}
