//HintName: Crucible.OrderItem.Entity.g.cs
// <auto-generated />
#nullable enable

namespace Sample;

public interface IOrderItemSnapshot
{
    string Sku { get; }
    Sample.OrderItemId Id { get; }
}

public partial class OrderItem
{
    internal void __HydrateFromSnapshot(IOrderItemSnapshot snapshot)
    {
        Sku = snapshot.Sku;
        Id = snapshot.Id;
    }

    public static global::Sample.OrderItem RehydrateFrom(IOrderItemSnapshot snapshot)
    {
        var entity = new global::Sample.OrderItem();
        entity.__HydrateFromSnapshot(snapshot);
        return entity;
    }
}
